# Generated by Django 6.1 on 2026-09-07 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_security_pin_user_two_factor_enabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Society Super Admin / President'), ('SECRETARY', 'Hon. Secretary'), ('TREASURER', 'Hon. Treasurer'), ('ACCOUNTANT', 'Society Accountant'), ('COMMITTEE', 'Management Committee Member'), ('FACILITY_MGR', 'Facility Manager'), ('OWNER', 'Flat Owner (Resident)'), ('TENANT', 'Tenant / Rented Person'), ('RESIDENT', 'Resident Member'), ('GUARD', 'Security Guard / Gatekeeper'), ('STAFF', 'Maintenance Staff / Technician')], default='RESIDENT', help_text='User role determines permissions and dashboard layout.', max_length=20),
        ),
    ]
