services:
  - type: web
    name: smartsociety-360
    env: python
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput"
    startCommand: "gunicorn society_core.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
