# Generated by Django 6.1 on 2026-09-03 17:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Standard Society Billing Policy', max_length=100)),
                ('base_rate_per_sqft', models.DecimalField(decimal_places=2, default=3.5, help_text='Rate per Sq. Ft. per month', max_digits=8)),
                ('sinking_fund_rate', models.DecimalField(decimal_places=2, default=0.5, help_text='Sinking fund per Sq. Ft.', max_digits=8)),
                ('fixed_amenities_fee', models.DecimalField(decimal_places=2, default=500.0, help_text='Fixed clubhouse/security fee', max_digits=8)),
                ('parking_slot_fee', models.DecimalField(decimal_places=2, default=300.0, help_text='Fee per vehicle parking slot', max_digits=8)),
                ('water_fixed_charge', models.DecimalField(decimal_places=2, default=400.0, max_digits=8)),
                ('late_fee_percentage', models.DecimalField(decimal_places=2, default=5.0, help_text='Penalty %% after due date', max_digits=5)),
                ('payment_grace_days', models.PositiveIntegerField(default=10, help_text='Days to pay from generation before late fee')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(max_length=50, unique=True)),
                ('billing_month', models.DateField(help_text='First day of the billing month e.g., 2026-09-01')),
                ('due_date', models.DateField()),
                ('base_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('sinking_fund', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('parking_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('water_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amenity_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('late_penalty', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('UNPAID', 'Unpaid'), ('PAID', 'Fully Paid'), ('PARTIAL', 'Partially Paid'), ('OVERDUE', 'Overdue')], default='UNPAID', max_length=20)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_bills', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_bills', to='properties.unit')),
            ],
            options={
                'ordering': ['-billing_month', 'unit__unit_number'],
                'unique_together': {('unit', 'billing_month')},
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, unique=True)),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI / Instant QR Code (GooglePay, PhonePe, Paytm)'), ('CARD', 'Debit / Credit Card (Visa, MasterCard, Amex)'), ('NETBANKING', 'Net Banking / NEFT / IMPS'), ('CASH', 'Cash Payment to Office'), ('CHEQUE', 'Cheque Deposit')], default='UPI', max_length=30)),
                ('payment_status', models.CharField(choices=[('SUCCESS', 'Payment Successful'), ('PENDING', 'Processing / Verification'), ('FAILED', 'Failed')], default='SUCCESS', max_length=20)),
                ('gateway_reference', models.CharField(blank=True, max_length=100)),
                ('payment_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True)),
                ('payer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.maintenancebill')),
            ],
        ),
        migrations.CreateModel(
            name='SocietyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('ELECTRICITY', 'Common Area Electricity & Generator Fuel'), ('WATER_SUPPLY', 'Municipal Water Supply & Tankers'), ('SECURITY', 'Security Agency Contract'), ('HOUSEKEEPING', 'Housekeeping & Waste Management'), ('LIFT_AMC', 'Elevator/Lift AMC Maintenance'), ('GARDENING', 'Gardening & Landscape Care'), ('REPAIRS', 'Civil, Plumbing & Electrical Repairs'), ('FESTIVAL', 'Festival, Cultural & Event Celebrations'), ('SALARIES', 'Staff Salaries & Bonuses'), ('ADMIN_EXPENSE', 'Office Administration & Audit Fees'), ('MISC', 'Miscellaneous Society Expenses')], default='REPAIRS', max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('expense_date', models.DateField(default=django.utils.timezone.now)),
                ('vendor_name', models.CharField(blank=True, max_length=150)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('is_approved', models.BooleanField(default=True)),
                ('receipt_doc', models.FileField(blank=True, null=True, upload_to='expenses/receipts/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_expenses', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-expense_date'],
            },
        ),
    ]
