# Generated by Django 6.1 on 2026-09-03 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g., Wing A - Sapphire Tower', max_length=50, unique=True)),
                ('code', models.CharField(help_text='Short code e.g., A, B, C', max_length=10, unique=True)),
                ('total_floors', models.PositiveIntegerField(default=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(help_text='e.g., A-101, B-402', max_length=20)),
                ('floor', models.PositiveIntegerField(default=1)),
                ('unit_type', models.CharField(choices=[('STUDIO', 'Studio Apartment'), ('1BHK', '1 BHK Flat'), ('2BHK', '2 BHK Flat'), ('3BHK', '3 BHK Luxury Flat'), ('4BHK', '4 BHK Grand Flat'), ('PENTHOUSE', 'Sky Penthouse'), ('VILLA', 'Independent Villa')], default='2BHK', max_length=20)),
                ('square_feet', models.PositiveIntegerField(default=1250, help_text='Carpet/Super built-up area in Sq. Ft.')),
                ('occupancy_status', models.CharField(choices=[('OWNER', 'Owner Occupied'), ('TENANT', 'Tenant Occupied'), ('VACANT', 'Vacant / Unoccupied')], default='OWNER', max_length=20)),
                ('parking_slot_number', models.CharField(blank=True, help_text='e.g., P-A102', max_length=30, null=True)),
                ('intercom_extension', models.CharField(blank=True, max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_units', to=settings.AUTH_USER_MODEL)),
                ('primary_resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resident_flats', to=settings.AUTH_USER_MODEL)),
                ('wing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='properties.wing')),
            ],
            options={
                'ordering': ['wing', 'floor', 'unit_number'],
                'unique_together': {('wing', 'unit_number')},
            },
        ),
        migrations.CreateModel(
            name='ResidentUnitMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('OWNER', 'Registered Owner'), ('TENANT', 'Tenant / Lease Holder'), ('FAMILY', 'Family Member / Dependent'), ('CO_OWNER', 'Co-Owner')], default='OWNER', max_length=20)),
                ('is_primary', models.BooleanField(default=True)),
                ('move_in_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_mappings', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resident_mappings', to='properties.unit')),
            ],
        ),
        migrations.CreateModel(
            name='DomesticStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role_type', models.CharField(choices=[('MAID', 'Housekeeper / Maid'), ('COOK', 'Chef / Cook'), ('DRIVER', 'Personal Driver'), ('NANNY', 'Nanny / Babysitter'), ('CLEANER', 'Car Cleaner'), ('TUTOR', 'Home Tutor'), ('OTHER', 'Other Daily Helper')], default='MAID', max_length=30)),
                ('phone_number', models.CharField(max_length=20)),
                ('passcode', models.CharField(help_text='Gate quick check-in 4-digit code', max_length=10, unique=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='staff/helpers/')),
                ('working_hours', models.CharField(default='08:00 AM - 04:00 PM', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_units', models.ManyToManyField(blank=True, related_name='domestic_staff_members', to='properties.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('CAR', 'Four Wheeler (Car/SUV)'), ('EV_CAR', 'Electric Car (EV)'), ('MOTORCYCLE', 'Two Wheeler / Motorcycle'), ('EV_SCOOTER', 'Electric Scooter / Bike'), ('BICYCLE', 'Bicycle')], default='CAR', max_length=20)),
                ('license_plate', models.CharField(help_text='e.g., MH-02-AB-1234 or NY-5849-ZZ', max_length=30, unique=True)),
                ('make_model', models.CharField(help_text='e.g., Honda Civic Silver, Tesla Model 3', max_length=100)),
                ('parking_slot', models.CharField(blank=True, max_length=30)),
                ('rfid_tag', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to='properties.unit')),
            ],
        ),
    ]
