# Generated by Django 6.1 on 2026-09-03 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoveInOutRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type', models.CharField(choices=[('MOVE_IN', 'Moving In (New Resident/Tenant)'), ('MOVE_OUT', 'Moving Out (Relocation)'), ('RENOVATION', 'Heavy Furniture / Interior Fit-Out')], default='MOVE_IN', max_length=20)),
                ('move_date', models.DateField()),
                ('time_slot', models.CharField(default='Morning (09:00 AM - 01:00 PM)', max_length=50)),
                ('service_lift_required', models.BooleanField(default=True, help_text='Reserve Service Elevator')),
                ('moving_company_name', models.CharField(blank=True, max_length=100)),
                ('vehicle_count', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Security Review'), ('APPROVED', 'Approved & Slot Reserved'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('security_deposit_paid', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_requests', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='move_requests', to='properties.unit')),
            ],
            options={
                'ordering': ['-move_date'],
            },
        ),
        migrations.CreateModel(
            name='RuleViolationReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('PARKING', 'Unauthorized / Blocked Parking'), ('NOISE', 'Late Night Noise / Loud Music'), ('PETS', 'Pet Policy / Common Area Mess'), ('TRASH', 'Improper Waste / Balcony Littering'), ('CORRIDOR', 'Corridor Obstruction / Shoe Racks'), ('OTHER', 'Other Society Rule Infraction')], default='PARKING', max_length=30)),
                ('description', models.TextField()),
                ('evidence_photo', models.ImageField(blank=True, null=True, upload_to='violations/')),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('UNDER_REVIEW', 'Under Committee Review'), ('NOTICE_ISSUED', 'Warning / Fine Issued'), ('RESOLVED', 'Resolved / Closed')], default='REPORTED', max_length=20)),
                ('action_taken', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_violations', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(help_text='Flat involved in violation', on_delete=django.db.models.deletion.CASCADE, related_name='rule_violations', to='properties.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
