# Generated by Django 6.1 on 2026-09-03 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LostAndFoundItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('KEYS', 'Keys & FOBs'), ('ELECTRONICS', 'Phones, Earbuds & Tech'), ('PETS', 'Lost / Rescued Pets'), ('DOCUMENTS', 'Cards, Wallets & IDs'), ('TOYS', 'Children Toys & Cycles'), ('ACCESSORIES', 'Watches, Glasses & Apparel'), ('OTHER', 'Other Belonging')], default='KEYS', max_length=30)),
                ('status', models.CharField(choices=[('LOST', 'Lost Item'), ('FOUND', 'Found Item'), ('CLAIMED', 'Claimed / Returned')], default='FOUND', max_length=20)),
                ('location', models.CharField(help_text='e.g. Garden Bench near Tower B, Clubhouse Gym', max_length=150)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='lost_found/')),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SocietyDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('BYELAWS', 'Society Bye-Laws & Rules'), ('AGM_MINUTES', 'AGM / SGM Meeting Minutes'), ('FINANCIAL', 'Audited Annual Balance Sheet'), ('FIRE_NOC', 'Fire Safety & Municipal NOC'), ('FITOUT', 'Renovation & Fit-out Guidelines'), ('OTHER', 'General Society Policy')], default='BYELAWS', max_length=30)),
                ('document_file', models.FileField(blank=True, null=True, upload_to='society_docs/')),
                ('file_size_text', models.CharField(default='1.2 MB PDF', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category', '-uploaded_at'],
            },
        ),
    ]
