# Generated by Django 6.1 on 2026-09-03 17:02

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Grand Banquet Hall, Infinity Pool, Squash Court', max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('category', models.CharField(default='Recreation', help_text='Sports, Wellness, Event, Leisure', max_length=50)),
                ('description', models.TextField()),
                ('capacity', models.PositiveIntegerField(default=50, help_text='Maximum guests allowed')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='₹0 for free amenities like Gym/Pool', max_digits=8)),
                ('location', models.CharField(default='Clubhouse Ground Floor', max_length=100)),
                ('open_time', models.TimeField(default=datetime.time(6, 0))),
                ('close_time', models.TimeField(default=datetime.time(22, 0))),
                ('rules', models.TextField(blank=True, help_text='Guidelines, dress code, cleaning deposit terms.')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='amenities/')),
                ('is_active', models.BooleanField(default=True)),
                ('requires_approval', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Amenities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='AmenityBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('guest_count', models.PositiveIntegerField(default=1)),
                ('purpose', models.CharField(blank=True, help_text='e.g. Birthday Party, Yoga session', max_length=200)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending Approval'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], default='CONFIRMED', max_length=20)),
                ('rejection_reason', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('amenity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='amenities.amenity')),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='amenity_bookings', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_amenity_bookings', to='properties.unit')),
            ],
            options={
                'ordering': ['-booking_date', '-start_time'],
            },
        ),
    ]
