# Generated by Django 6.1 on 2026-09-03 17:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0001_initial'),
        ('properties', '0002_moveinoutrequest_ruleviolationreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EVChargingStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(help_text='e.g. Station A-EV1 (Basement 1, Pole 14)', max_length=100)),
                ('power_kw', models.DecimalField(decimal_places=1, default=7.4, help_text='Capacity in kW', max_digits=5)),
                ('connector_type', models.CharField(choices=[('TYPE_2', 'Type 2 AC (Fast 7.4 kW - 22 kW)'), ('CCS2', 'CCS2 DC Fast Charger (50 kW)'), ('CHAdeMO', 'CHAdeMO DC Fast (50 kW)'), ('SOCKET_15A', '15A Standard 3-Pin Socket')], default='TYPE_2', max_length=30)),
                ('location', models.CharField(default='Basement Level 1 - Bay EV', max_length=100)),
                ('kwh_rate', models.DecimalField(decimal_places=2, default=12.5, help_text='Cost per kWh (₹)', max_digits=6)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('CHARGING', 'Currently In Use / Charging'), ('MAINTENANCE', 'Under Maintenance')], default='AVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EVChargingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField(default=django.utils.timezone.now)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('units_consumed_kwh', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('status', models.CharField(choices=[('RESERVED', 'Slot Reserved'), ('ACTIVE', 'Charging in Progress'), ('COMPLETED', 'Completed / Billed'), ('CANCELLED', 'Cancelled')], default='RESERVED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ev_charges', to='properties.unit')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ev_sessions', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='properties.vehicle')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='amenities.evchargingstation')),
            ],
            options={
                'ordering': ['-booking_date', '-start_time'],
            },
        ),
    ]
