# Generated by Django 6.1 on 2026-09-03 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('PLUMBING', 'Plumbing / Water Leakage'), ('ELECTRICAL', 'Electrical / Power Issue'), ('ELEVATOR', 'Elevator / Lift Malfunction'), ('CARPENTRY', 'Carpentry / Doors & Windows'), ('PEST_CONTROL', 'Pest Control & Fumigation'), ('SECURITY', 'Security / Intercom / CCTV'), ('COMMON_AREA', 'Common Area Lighting / Cleaning'), ('GARDEN', 'Gardening & Lawns'), ('OTHER', 'General / Other Service Request')], default='PLUMBING', max_length=30)),
                ('priority', models.CharField(choices=[('LOW', 'Low (Routine request)'), ('MEDIUM', 'Medium (Standard)'), ('HIGH', 'High (Important)'), ('URGENT', 'Urgent (Immediate Attention Needed)')], default='MEDIUM', max_length=20)),
                ('status', models.CharField(choices=[('OPEN', 'Open / Logged'), ('IN_PROGRESS', 'In Progress / Assigned'), ('RESOLVED', 'Resolved / Completed'), ('CLOSED', 'Closed')], default='OPEN', max_length=20)),
                ('description', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='helpdesk/tickets/')),
                ('resolution_notes', models.TextField(blank=True)),
                ('rating', models.PositiveSmallIntegerField(blank=True, help_text='Resident 1 to 5 star rating', null=True)),
                ('resident_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raised_tickets', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_tickets', to='properties.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('attachment', models.FileField(blank=True, null=True, upload_to='helpdesk/comments/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='helpdesk.maintenanceticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
