# Generated by Django 6.1 on 2026-09-03 17:02

import apps.gatekeeper.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=100)),
                ('courier_company', models.CharField(choices=[('AMAZON', 'Amazon'), ('FLIPKART', 'Flipkart'), ('SWIGGY', 'Swiggy / Instamart'), ('ZOMATO', 'Zomato / Blinkit'), ('DHL', 'DHL / BlueDart'), ('FEDEX', 'FedEx / Delhivery'), ('OTHER', 'Other Courier')], default='AMAZON', max_length=30)),
                ('tracking_number', models.CharField(blank=True, max_length=100)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('collected_at', models.DateTimeField(blank=True, null=True)),
                ('is_collected', models.BooleanField(default=False)),
                ('collected_by', models.CharField(blank=True, max_length=100)),
                ('guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='properties.unit')),
            ],
            options={
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PreApprovedPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pass_code', models.CharField(default=apps.gatekeeper.models.generate_passcode, max_length=10, unique=True)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_phone', models.CharField(blank=True, max_length=20)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_until', models.DateTimeField()),
                ('purpose', models.CharField(default='Personal Visit', max_length=200)),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('host_resident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_passes', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preapproved_passes', to='properties.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('MEDICAL', 'Medical Emergency / Ambulance'), ('FIRE', 'Fire Alarm / Smoke Hazard'), ('SECURITY', 'Security Breach / Intruder'), ('ELEVATOR', 'Elevator / Lift Stuck'), ('GAS_LEAK', 'LPG Gas Leakage Alert'), ('OTHER', 'General Urgent Alert')], default='MEDICAL', max_length=30)),
                ('location_details', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField(blank=True)),
                ('is_resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_sos_alerts', to=settings.AUTH_USER_MODEL)),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggered_sos_alerts', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_alerts', to='properties.unit')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VisitorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitor_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('visitor_type', models.CharField(choices=[('GUEST', 'Guest / Family Friend'), ('DELIVERY', 'Delivery Agent (Amazon, Food, Courier)'), ('CAB', 'Cab / Taxi (Uber, Ola, Lyft)'), ('SERVICE', 'Service Technician / Contractor'), ('INTERVIEW', 'Official / Interview / Business'), ('OTHER', 'Other Visitor')], default='GUEST', max_length=20)),
                ('vehicle_number', models.CharField(blank=True, help_text='Visitor Vehicle (if any)', max_length=30, null=True)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('entry_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('exit_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('INSIDE', 'Currently Inside Society'), ('CHECKED_OUT', 'Checked Out / Departed'), ('DENIED', 'Entry Denied by Resident / Guard')], default='INSIDE', max_length=20)),
                ('is_pre_approved', models.BooleanField(default=False)),
                ('entry_guard', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guard_checked_entries', to=settings.AUTH_USER_MODEL)),
                ('host_resident', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_visitors', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitors', to='properties.unit')),
            ],
            options={
                'ordering': ['-entry_time'],
            },
        ),
    ]
